[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
# serde
serde = {version = "1.0", features = ["derive"]}
bincode = "1.3.3"
tokio-tungstenite = "0.17.1"

