[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
# serde
serde = {workspace = true, features=["derive"]}
serde_json = {workspace = true}
bincode = {workspace = true}
tokio-tungstenite = {workspace = true}